### ISSUE TITLE
Next14 & @supabase/ssr: AuthApiError: invalid flow state, no valid flow state found

### ISSUE THREAD

**Issue by lukerep** [supabase/auth-helpers#705]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug
- When using the Google Oauth provider, after being redirected from Google I receive the following error:
```
 ⨯ AuthApiError: invalid flow state, no valid flow state found
    at handleError (webpack-internal:///(rsc)/./node_modules/@supabase/gotrue-js/dist/module/lib/fetch.js:45:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async _handleRequest (webpack-internal:///(rsc)/./node_modules/@supabase/gotrue-js/dist/module/lib/fetch.js:92:9)
    at async _request (webpack-internal:///(rsc)/./node_modules/@supabase/gotrue-js/dist/module/lib/fetch.js:72:18)
    at async SupabaseAuthClient._exchangeCodeForSession (webpack-internal:///(rsc)/./node_modules/@supabase/gotrue-js/dist/module/GoTrueClient.js:403:33)
    at async eval (webpack-internal:///(rsc)/./node_modules/@supabase/gotrue-js/dist/module/GoTrueClient.js:824:28) {
  __isAuthError: true,
  status: 403
}
```

My `src/app/auth/callback/route.ts` file looks like so:
```typescript
import { createServerClient, type CookieOptions } from "@supabase/ssr";
import { cookies } from "next/headers";
import { type NextRequest, NextResponse } from "next/server";
import { env } from "~/env";

export async function GET(request: NextRequest) {
  const { searchParams, origin } = new URL(request.url);
  const code = searchParams.get("code");
  // if "next" is in param, use it as the redirect URL
  const next = searchParams.get("next") ?? "/";

  if (code) {
    const cookieStore = cookies();
    const supabase = createServerClient(
      env.NEXT_PUBLIC_SUPABASE_URL,
      env.NEXT_PUBLIC_SUPABASE_ANON_KEY,
      {
        cookies: {
          get(name: string) {
            return cookieStore.get(name)?.value;
          },
          set(name: string, value: string, options: CookieOptions) {
            cookieStore.set({ name, value, ...options });
          },
          remove(name: string, options: CookieOptions) {
            cookieStore.delete({ name, ...options });
          },
        },
      },
    );
    const { error } = await supabase.auth.exchangeCodeForSession(code);
    if (!error) {
      return NextResponse.redirect(`${origin}${next}`);
    }
  }

  // return the user to an error page with instructions
  return NextResponse.redirect(`${origin}/auth/auth-code-error`);
}
```

Seems like `user_id` is `null` in `auth.flow_state` table:
![image](https://github.com/supabase/auth-helpers/assets/50653587/fddf7edf-f9bc-4b8f-92e3-d28b8568f45c)

Other people have reported the same problem.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Click login with Google
2. Get redirected to Google with a selection of my accounts
3. Select an account
4. Get redirected to my `/auth/callback` endpoint with `code` query param and other params
5. The error shown earlier is the result

## Expected behavior

- The user is logged in successfully via Google Oauth

## System information

- OS: [Windows]
- Browser [chrome]
- Version of supabase-js: [2.39.0]
- Version of supabase/ssr: [0.0.10]
- Version of NextJS [14.0.3]
- Version of Node.js: [18.19.0]

**Comment by litewarp** [comment]
I'm having the same issue after being redirected back to my app. I get a 403 invaid flow state. 

When I check my auth.flow_state table, the user_id's are missing as well.

![image](https://github.com/supabase/auth-helpers/assets/1900476/b670c5c5-0522-4117-94d8-0b07174d672e)

**Comment by lukerep** [comment]
I ended up getting it working.

@litewarp Is your redirect URL going directly to your app or to your Supabase instance?

**Comment by litewarp** [comment]
> @litewarp Is your redirect URL going directly to your app or to your Supabase instance?

To a route handler in my app -- `http://localhost:3000/auth/callback`

I wonder if this can't be used for first-time signup since there's no user yet?

**Comment by lukerep** [comment]
@litewarp 
You need to point it to your supabase:
`http://localhost:54321/auth/v1/callback`

Example `config.toml`
```toml
[auth.external.google]
enabled = true
client_id = "env(SUPABASE_AUTH_EXTERNAL_GOOGLE_CLIENT)"
secret = "env(SUPABASE_AUTH_EXTERNAL_GOOGLE_SECRET)"
# Overrides the default auth redirectUrl.
redirect_uri = "http://localhost:54321/auth/v1/callback"
```

and 

```toml
[auth]
enabled = true
# The base URL of your website. Used as an allow-list for redirects and for constructing URLs used
# in emails.
site_url = "http://localhost:3000"
# A list of *exact* URLs that auth providers are permitted to redirect to post authentication.
additional_redirect_urls = ["http://localhost:54321/auth/v1/callback"]
```

Then in your auth component when signing in with OAuth it should look like this:

```typescript
const handleSignInWithGoogle = async () => {
    await supabase.auth.signInWithOAuth({
      provider: "google",
      options: {
        redirectTo: `${location.origin}/auth/callback`, // This redirects to your NextJS route
        queryParams: {
          access_type: "offline",
          prompt: "consent",
        },
      },
    });
  };
```

**Comment by litewarp** [comment]
So, it's mostly working. I can complete sign-in and get the code back from the auth flow, but I can't seem to get the redirectTo option to work. It just returns me to the root with "?code=XXXXXX" in the url instead of sending me to the nextjs callback route. I'm using Auth UI so maybe there's something lost between that and when goTrue issues the command. 

```toml
[auth.external.google]
enabled = true
client_id = "env(GOOGLE_CLIENT_ID)"
secret = "env(GOOGLE_CLIENT_SECRET)"
# Overrides the default auth redirectUrl.
redirect_uri = "http://localhost:54321/auth/v1/callback"
# Overrides the default auth provider URL. Used to support self-hosted gitlab, single-tenant Azure,
# or any other third-party OIDC providers.
url = ""
```

```toml
[auth]
enabled = true
# The base URL of your website. Used as an allow-list for redirects and for constructing URLs used
# in emails.
site_url = "http://localhost:3000"
# A list of *exact* URLs that auth providers are permitted to redirect to post authentication.
additional_redirect_urls = [ "http://localhost:54321/auth/v1/callback"]
# How long tokens are valid for, in seconds. Defaults to 3600 (1 hour), maximum 604,800 seconds (one
# week).
jwt_expiry = 3600
# Allow/disallow new user signups to your project.
enable_signup = true
```

```tsx
   <Auth
      supabaseClient={supabase}
      appearance={{ theme: ThemeSupa }}
      providers={["google"]}
      theme={"dark"}
      queryParams={{
        access_type: "offline",
        prompt: "consent",
      }}
      providerScopes={{
        google: ["https://www.googleapis.com/auth/userinfo.profile"].join(", "),
      }}
      redirectTo={`${redirectBase}/auth/callback`}
      onlyThirdPartyProviders
    />
```
